_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
